
name: FSL-React-App-Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v3

    - name: Installing node-js 14.x
    - run: |
        apt -y update
        apt -y install nodejs
        node --version

    # - name: verifying files and path
    #   run: |
    #     pwd
    #     ls -ltrh

    # - name: Build react app
    #   run: |
    #     npm install
    #     npm run lint
    #     npm run prettier
    #     CI=true npm run test
    #     npm run build
        
