
name: FSL-React-App-Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Installing node-js 14.x
        run: |
          sudo apt -y update
          sudo apt -y install nodejs
          node --version

      - name: verifying files and path
        run: |
          pwd
          ls -ltrh

      - name: Build react app
        run: |
          cd rdicidr-0.1.0
          npm install
          npm run lint
          npm run prettier
          CI=true npm run test
          npm run build
        
